import { ITableItemData } from "../interfaces/tableData.interface";

export interface ITableData {
  tableTitleStatistics: string[];
  tableTitleActions: string[];
  players: ITableItemData[];
  statisticsTitle: string;
  actionsTitle: string;
}

export const TABLE_DATA1: ITableData = {
  statisticsTitle: "Основная статистика",
  actionsTitle: "Атаки",
  tableTitleStatistics: [
    "Игрок",
    "Минут на поле",
    "Голы",
    "Голевые передачи",
    "Действия/ удачные",
    "Удары/ в створ",
    "XG ударов",
    "Фолы/ на нем",
    "Офсайды",
    "Желтые/ красные карточки",
  ],
  tableTitleActions: [
    "Игрок",
    "Минут на поле",
    "ТТД",
    "ТТД в штрафной",
    "Голевые моменты/ завершенные",
    "Создание голевого момента",
    "Потери мяча/ на своей половине",
    "Возвраты мяча/ на чужой половине",
    "Неудачные обработки мяча",
  ],
  players: [
    {
      id: 1,
      number: 25,
      name: "Д. Баринов",
      minutes: 96,
      goals: 2,
      goalsPass: 1,
      actions: 6,
      luckyActions: 3,
      shots: 2,
      shotsOnTarget: 2,
      coefficient: 0.2,
      fouls: 5,
      foulsOn: 3,
      offsides: 2,
      yellowCard: 0,
      redCard: 0,
      actionsOnPenalty: 2,
      scoringChances: 1,
      scoringChancesComplete: 6,
      scoringChancesCreate: 3,
      loss: 5,
      lossOnOwn: 2,
      returnBall: 23,
      returnBallOpponentHalf: 5,
      poorBall: 3,
    },
    {
      id: 2,
      number: 25,
      name: "Д. Баринов",
      minutes: 96,
      goals: 2,
      goalsPass: 1,
      actions: 64,
      luckyActions: 53,
      shots: 7,
      shotsOnTarget: 3,
      coefficient: 0.2,
      fouls: 5,
      foulsOn: 3,
      offsides: 2,
      yellowCard: 0,
      redCard: 0,
      actionsOnPenalty: 2,
      scoringChances: 1,
      scoringChancesComplete: 6,
      scoringChancesCreate: 3,
      loss: 5,
      lossOnOwn: 2,
      returnBall: 23,
      returnBallOpponentHalf: 5,
      poorBall: 3,
    },
    {
      id: 3,
      number: 25,
      name: "Д. Баринов",
      minutes: 96,
      goals: 2,
      goalsPass: 1,
      actions: 6,
      luckyActions: 3,
      shots: 5,
      shotsOnTarget: 2,
      coefficient: 0.2,
      fouls: 5,
      foulsOn: 3,
      offsides: 2,
      yellowCard: 0,
      redCard: 0,
      actionsOnPenalty: 2,
      scoringChances: 1,
      scoringChancesComplete: 6,
      scoringChancesCreate: 3,
      loss: 5,
      lossOnOwn: 2,
      returnBall: 23,
      returnBallOpponentHalf: 5,
      poorBall: 3,
    },
    {
      id: 4,
      number: 25,
      name: "Д. Баринов",
      minutes: 96,
      goals: 2,
      goalsPass: 1,
      actions: 6,
      luckyActions: 3,
      shots: 5,
      shotsOnTarget: 2,
      coefficient: 0.2,
      fouls: 5,
      foulsOn: 3,
      offsides: 2,
      yellowCard: 0,
      redCard: 0,
      actionsOnPenalty: 2,
      scoringChances: 1,
      scoringChancesComplete: 6,
      scoringChancesCreate: 3,
      loss: 5,
      lossOnOwn: 2,
      returnBall: 23,
      returnBallOpponentHalf: 5,
      poorBall: 3,
    },
    {
      id: 5,
      number: 25,
      name: "Д. Баринов",
      minutes: 96,
      goals: 2,
      goalsPass: 1,
      actions: 6,
      luckyActions: 3,
      shots: 5,
      shotsOnTarget: 2,
      coefficient: 0.2,
      fouls: 5,
      foulsOn: 3,
      offsides: 2,
      yellowCard: 0,
      redCard: 0,
      actionsOnPenalty: 2,
      scoringChances: 1,
      scoringChancesComplete: 6,
      scoringChancesCreate: 3,
      loss: 5,
      lossOnOwn: 2,
      returnBall: 23,
      returnBallOpponentHalf: 5,
      poorBall: 3,
    },
  ],
};
export const TABLE_DATA2: ITableData = {
  statisticsTitle: "Основная статистика",
  actionsTitle: "Атаки",
  tableTitleStatistics: [
    "Игрок",
    "Минут на поле",
    "Голы",
    "Голевые передачи",
    "Действия/ удачные",
    "Удары/ в створ",
    "XG ударов",
    "Фолы/ на нем",
    "Офсайды",
    "Желтые/ красные карточки",
  ],
  tableTitleActions: [
    "Игрок",
    "Минут на поле",
    "ТТД",
    "ТТД в штрафной",
    "Голевые моменты/ завершенные",
    "Создание голевого момента",
    "Потери мяча/ на своей половине",
    "Возвраты мяча/ на чужой половине",
    "Неудачные обработки мяча",
  ],
  players: [
    {
      id: 1,
      number: 49,
      name: "М. Караев",
      minutes: 85,
      goals: 4,
      goalsPass: 2,
      actions: 9,
      luckyActions: 4,
      shots: 8,
      shotsOnTarget: 4,
      coefficient: 0.234,
      fouls: 8,
      foulsOn: 6,
      offsides: 4,
      yellowCard: 0,
      redCard: 0,
      actionsOnPenalty: 6,
      scoringChances: 4,
      scoringChancesComplete: 10,
      scoringChancesCreate: 8,
      loss: 7,
      lossOnOwn: 4,
      returnBall: 23,
      returnBallOpponentHalf: 8,
      poorBall: 6,
    },
    {
      id: 2,
      number: 49,
      name: "М. Караев",
      minutes: 85,
      goals: 4,
      goalsPass: 2,
      actions: 9,
      luckyActions: 4,
      shots: 8,
      shotsOnTarget: 4,
      coefficient: 0.234,
      fouls: 8,
      foulsOn: 6,
      offsides: 4,
      yellowCard: 0,
      redCard: 0,
      actionsOnPenalty: 6,
      scoringChances: 4,
      scoringChancesComplete: 10,
      scoringChancesCreate: 8,
      loss: 7,
      lossOnOwn: 4,
      returnBall: 23,
      returnBallOpponentHalf: 8,
      poorBall: 6,
    },
    {
      id: 3,
      number: 49,
      name: "М. Караев",
      minutes: 85,
      goals: 4,
      goalsPass: 2,
      actions: 9,
      luckyActions: 4,
      shots: 8,
      shotsOnTarget: 4,
      coefficient: 0.234,
      fouls: 8,
      foulsOn: 6,
      offsides: 4,
      yellowCard: 0,
      redCard: 0,
      actionsOnPenalty: 6,
      scoringChances: 4,
      scoringChancesComplete: 10,
      scoringChancesCreate: 8,
      loss: 7,
      lossOnOwn: 4,
      returnBall: 23,
      returnBallOpponentHalf: 8,
      poorBall: 6,
    },
    {
      id: 4,
      number: 49,
      name: "М. Караев",
      minutes: 85,
      goals: 4,
      goalsPass: 2,
      actions: 9,
      luckyActions: 4,
      shots: 8,
      shotsOnTarget: 4,
      coefficient: 0.234,
      fouls: 8,
      foulsOn: 6,
      offsides: 4,
      yellowCard: 0,
      redCard: 0,
      actionsOnPenalty: 6,
      scoringChances: 4,
      scoringChancesComplete: 10,
      scoringChancesCreate: 8,
      loss: 7,
      lossOnOwn: 4,
      returnBall: 23,
      returnBallOpponentHalf: 8,
      poorBall: 6,
    },
    {
      id: 5,
      number: 49,
      name: "М. Караев",
      minutes: 85,
      goals: 4,
      goalsPass: 2,
      actions: 9,
      luckyActions: 4,
      shots: 8,
      shotsOnTarget: 4,
      coefficient: 0.234,
      fouls: 8,
      foulsOn: 6,
      offsides: 4,
      yellowCard: 0,
      redCard: 0,
      actionsOnPenalty: 6,
      scoringChances: 4,
      scoringChancesComplete: 10,
      scoringChancesCreate: 8,
      loss: 7,
      lossOnOwn: 4,
      returnBall: 23,
      returnBallOpponentHalf: 8,
      poorBall: 6,
    },
  ],
};
